domain_path: /home/kaki/projects/projects/aobo_pgd/uart/uart_platform/zynqmp_fsbl/zynqmp_fsbl_bsp
app_src_dir: /fpga/installation/2025.1/Vitis/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
template: zynqmp_fsbl
lang: c
