domain_path: /home/kaki/projects/projects/aobo_pgd/uart/uart_platform/export/uart_platform/sw/standalone_psu_cortexa53_0
app_src_dir: /fpga/installation/2025.1/Vitis/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
